language: python
sudo: required

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis
script:
  # install latest libgit2 from source, hoping that pygit2 will _not_ have a problem with it
  - git clone https://github.com/libgit2/libgit2
  - pushd libgit2; mkdir build/; cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install -j$(nproc)
  - popd
  # run tests
  - tox

jobs:
  include:
    - stage: package
      install:
      - wget https://raw.githubusercontent.com/AppImage/AppImages/master/set-up-ppas.sh -O- | sudo bash -x
      - sudo apt install -y --force-yes curl libcurl3 libcurl-gnutls3 libcurl-nss3
      script:
      - mkdir -p build
      - cd build
      - bash -xe ../build-appimage.sh

stages:
  - test
  - package
