language: python
sudo: required

python:
  - "3.5"
  - "3.6"

install:
  # install tox and its wrapper tox-travis
  - pip install tox-travis
  # install latest libgit2 from source, hoping that pygit2 will _not_ have a problem with it
  - git clone https://github.com/libgit2/libgit2
  - pushd libgit2; mkdir build/; cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install -j$(nproc)
  - popd
script:
  # run tests
  - tox

jobs:
  include:
    - stage: package
      install:
      # disabling until we have a working libcurl in the PPA
      # un-bundling system libcurl in the AppImage build script for the same reason
      # - wget https://raw.githubusercontent.com/AppImage/AppImages/master/set-up-ppas.sh -O- | sudo bash -x
      # - sudo apt install -y --force-yes curl libcurl3 libcurl-gnutls3 libcurl-nss3
      script:
      - mkdir -p build
      - cd build
      - bash -xe ../build-appimage.sh
      # pretend PR to upload to transfer.sh -- TODO: remove this line after merging
      - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - chmod +x upload.sh
      - env TRAVIS_EVENT_TYPE=pull_request bash upload.sh Pext*.AppImage*

stages:
  - test
  - package
