sudo: required
language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis

before_script:
  - bash travis/install-deps.sh

# for test stage
script:
  - tox -v

jobs:
  include:
    - stage: packaging
      sudo: required
      before_script:
        - bash travis/install-deps.sh
      script:
        # build AppImage
        - mkdir -p build
        - cd build
        - bash -xe ../travis/build-appimage.sh
        # test AppImage
        - chmod +x Pext*.AppImage
        # temporary solution for
        # $ ./Pext*.AppImage --version
        # QXcbConnection: Could not connect to display
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - ./Pext*.AppImage --version
      after_success:
        # pretend PR to upload to transfer.sh -- TODO: remove this line after merging
        - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
        - env TRAVIS_EVENT_TYPE=pull_request bash upload.sh Pext*.AppImage*
